import { groq } from "next-sanity";

export const SERVICE_PAGE_QUERY = groq`
  *[_type == "servicePage" && slug.current == $slug][0]{
    _id,
    title,
    "slug": slug.current,
    category,
    kicker,
    heroHeadline,
    heroSubheadline,
    heroImage{
      asset->{
        _id,
        url,
        altText,
        metadata{
          dimensions{
            width,
            height,
            aspectRatio
          }
        }
      }
    },
    problemHeadline,
    problemDescription,
    solutionDescription,
    capabilities[]{
      title,
      description,
      image{
        asset->{
          _id,
          url,
          altText,
          metadata{
            dimensions{
              width,
              height,
              aspectRatio
            }
          }
        }
      }
    },
    featuresSection{
      kicker,
      title,
      description,
      image{
        asset->{
          _id,
          url,
          altText,
          metadata{
            dimensions{
              width,
              height,
              aspectRatio
            }
          }
        }
      },
      items[]{
        image{
          asset->{
            _id,
            url,
            altText,
            metadata{
              dimensions{
                width,
                height,
                aspectRatio
              }
            }
          }
        },
        title,
        description
      }
    },
    additionalSections[]{
      kicker,
      title,
      description,
      media{
        type,
        image{
          asset->{
            _id,
            url,
            altText,
            metadata{
              dimensions{
                width,
                height,
                aspectRatio
              }
            }
          }
        },
        videoUrl,
        videoFile{
          asset->{
            _id,
            url
          }
        }
      },
      alignment
    },
    proofKicker,
    proofMetric,
    proofContext,
    proofBody,
    proofCaseStudyLink->{
      title,
      "slug": slug.current,
      kicker,
      metricLarge,
      metricContext
    },
    ctaHeadline,
    ctaBody,
    metaTitle,
    metaDescription
  }
`;

export const ALL_SERVICES_QUERY = groq`
  *[_type == "servicePage"] | order(_createdAt asc){
    _id,
    title,
    "slug": slug.current,
    category,
    heroHeadline,
    heroSubheadline,
    metaDescription
  }
`;

export const CASE_STUDIES_QUERY = groq`
  *[_type == "caseStudy"] | order(_createdAt desc){
    _id,
    title,
    "slug": slug.current,
    kicker,
    cardHeadline,
    metricLarge,
    metricContext,
    industry,
    executionType,
    featuredImage{
      asset->{
        _id,
        url,
        altText
      }
    },
    featuredMedia{
      type,
      image{
        asset->{
          _id,
          url,
          altText
        }
      },
      videoFile{
        asset->{
          _id,
          url
        }
      },
      videoUrl
    }
  }
`;

export const CASE_STUDY_QUERY = groq`
  *[_type == "caseStudy" && slug.current == $slug][0]{
    _id,
    title,
    "slug": slug.current,
    kicker,
    cardHeadline,
    metricLarge,
    metricContext,
    industry,
    executionType,
    challenge,
    solution,
    results,
    technologiesUsed,
    clientQuotes[]{
      text,
      name,
      designation
    },
    featuredImage{
      asset->{
        _id,
        url,
        altText
      }
    },
    featuredMedia{
      type,
      image{
        asset->{
          _id,
          url,
          altText
        }
      },
      videoFile{
        asset->{
          _id,
          url
        }
      },
      videoUrl
    },
    seo{
      title,
      description
    }
  }
`;

export const ENGAGEMENT_MODELS_QUERY = groq`
  *[_type == "engagementModel"] | order(_createdAt asc){
    _id,
    title,
    summary,
    pillars,
    ctaLabel
  }
`;

export const TECHNOLOGY_PARTNERS_QUERY = groq`
  *[_type == "technologyPartner"] | order(name asc){
    _id,
    name,
    logo{
      asset->{
        _id,
        url,
        altText
      }
    },
    website,
    excerpt,
    categories
  }
`;

export const ARTICLES_QUERY = groq`
  *[_type == "article"] | order(publishedAt desc){
    _id,
    title,
    "slug": slug.current,
    publishedAt,
    excerpt,
    heroImage{
      asset->{
        _id,
        url,
        altText
      }
    },
    seo{
      title,
      description
    }
  }
`;

export const ARTICLE_QUERY = groq`
  *[_type == "article" && slug.current == $slug][0]{
    _id,
    _updatedAt,
    title,
    "slug": slug.current,
    publishedAt,
    excerpt,
    heroImage{
      asset->{
        _id,
        url,
        altText
      }
    },
    body,
    seo{
      title,
      description,
      ogImage{
        asset->{
          _id,
          url
        }
      }
    }
  }
`;

export const EXECUTION_PAGE_QUERY = groq`
  *[_type == "executionPage"][0]{
    _id,
    title,
    metaTitle,
    metaDescription,
    heroKicker,
    heroHeadline,
    heroSubheadline,
    servicesLabel,
    servicesTitle,
    servicesDescription,
    services[]{
      number,
      title,
      description,
      outcome
    },
    ctaHeadline,
    ctaBody,
    ctaLabel
  }
`;

export const DELIVERED_VALUE_PAGE_QUERY = groq`
  *[_type == "deliveredValuePage"][0]{
    _id,
    title,
    metaTitle,
    metaDescription,
    heroKicker,
    heroHeadline,
    heroSubheadline,
    storiesLabel,
    storiesTitle,
    stories[]{
      client,
      metricValue,
      metricContext,
      description,
      videoLink{
        href,
        label
      }
    },
    ctaHeadline,
    ctaBody,
    ctaLabel
  }
`;

export const HOMEPAGE_QUERY = groq`
  *[_type == "homepage"][0]{
    _id,
    heroMetrics[]{
      value,
      label
    },
    statsItems,
    accountabilityGapTitle,
    accountabilityGapBody,
    modelItems[]{
      number,
      title,
      description
    },
    deliveredStories[]{
      client,
      metricValue,
      metricContext,
      description,
      videoLink{
        href,
        label
      }
    },
    recognitionItems[]{
      label,
      title,
      source
    },
    services[]{
      number,
      title,
      description,
      outcome
    },
    partners[]{
      name,
      color
    },
    industries[]{
      name,
      description
    },
    contactTitle,
    contactDescription,
    contactCtaLabel,
    seo{
      title,
      description
    }
  }
`;

export const CATEGORIES_QUERY = groq`
  *[_type == "category"] | order(key asc){
    _id,
    key,
    label,
    description,
    image{
      asset->{
        _id,
        url,
        altText,
        metadata{
          dimensions{
            width,
            height,
            aspectRatio
          }
        }
      }
    }
  }
`;

export const ABOUT_US_PAGE_QUERY = groq`
  *[_type == "aboutUsPage"][0]{
    _id,
    heroLabel,
    heroTitle,
    heroDescription,
    missionTitle,
    missionContent,
    visionTitle,
    visionContent,
    valuesTitle,
    values[]{
      title,
      description
    },
    leadershipTitle,
    leadershipDescription,
    leadershipTeam[]{
      name,
      title,
      image{
        asset->{
          _id,
          url,
          altText,
          metadata{
            dimensions{
              width,
              height,
              aspectRatio
            }
          }
        }
      },
      bio
    },
    certificationsTitle,
    certifications[]{
      category,
      image{
        asset->{
          _id,
          url,
          altText,
          metadata{
            dimensions{
              width,
              height,
              aspectRatio
            }
          }
        }
      },
      items[]{
        name,
        image{
          asset->{
            _id,
            url,
            altText,
            metadata{
              dimensions{
                width,
                height,
                aspectRatio
              }
            }
          }
        }
      }
    },
    awards[]{
      name,
      image{
        asset->{
          _id,
          url,
          altText,
          metadata{
            dimensions{
              width,
              height,
              aspectRatio
            }
          }
        }
      }
    },
    ctaTitle,
    ctaDescription,
    ctaLabel,
    seo{
      title,
      description,
      keywords,
      ogImage{
        asset->{
          _id,
          url
        }
      }
    }
  }
`;
