/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ContactSubmission = {
  _id: string;
  _type: "contactSubmission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  company?: string;
  message?: string;
  utm?: {
    source?: string;
    medium?: string;
    campaign?: string;
  };
  submittedAt?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  defaultOgImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  contactEmail?: string;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type TechnologyPartner = {
  _id: string;
  _type: "technologyPartner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  excerpt?: string;
  categories?: Array<string>;
};

export type EngagementModel = {
  _id: string;
  _type: "engagementModel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  summary?: string;
  pillars?: Array<string>;
  ctaLabel?: string;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  excerpt?: string;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  seo?: {
    title?: string;
    description?: string;
    ogImage?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type ServicePage = {
  _id: string;
  _type: "servicePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  kicker?: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  problemHeadline?: string;
  problemDescription?: string;
  solutionDescription?: string;
  capabilities?: Array<{
    title?: string;
    description?: string;
    _type: "capability";
    _key: string;
  }>;
  proofKicker?: string;
  proofMetric?: string;
  proofContext?: string;
  proofBody?: string;
  proofCaseStudyLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "caseStudy";
  };
  ctaHeadline?: string;
  ctaBody?: string;
  metaTitle?: string;
  metaDescription?: string;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  kicker?: string;
  cardHeadline?: string;
  metricLarge?: string;
  metricContext?: string;
  industry?: "financial" | "healthcare" | "manufacturing" | "energy" | "retail";
  executionType?: "cloud" | "ai-data" | "digital-product" | "core-systems";
  challenge?: string;
  solution?: string;
  results?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  technologiesUsed?: Array<string>;
  featuredImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = ContactSubmission | SiteSettings | TechnologyPartner | EngagementModel | Article | ServicePage | CaseStudy | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: src/lib/sanity.queries.ts
// Variable: SERVICE_PAGE_QUERY
// Query: *[_type == "servicePage" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    kicker,    heroHeadline,    heroSubheadline,    problemHeadline,    problemDescription,    solutionDescription,    capabilities[]{      title,      description    },    proofKicker,    proofMetric,    proofContext,    proofBody,    proofCaseStudyLink->{      title,      "slug": slug.current,      kicker,      metricLarge,      metricContext    },    ctaHeadline,    ctaBody,    metaTitle,    metaDescription  }
export type SERVICE_PAGE_QUERYResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  kicker: string | null;
  heroHeadline: string | null;
  heroSubheadline: string | null;
  problemHeadline: string | null;
  problemDescription: string | null;
  solutionDescription: string | null;
  capabilities: Array<{
    title: string | null;
    description: string | null;
  }> | null;
  proofKicker: string | null;
  proofMetric: string | null;
  proofContext: string | null;
  proofBody: string | null;
  proofCaseStudyLink: {
    title: string | null;
    slug: string | null;
    kicker: string | null;
    metricLarge: string | null;
    metricContext: string | null;
  } | null;
  ctaHeadline: string | null;
  ctaBody: string | null;
  metaTitle: string | null;
  metaDescription: string | null;
} | null;
// Variable: CASE_STUDIES_QUERY
// Query: *[_type == "caseStudy"] | order(_createdAt desc){    _id,    title,    "slug": slug.current,    kicker,    cardHeadline,    metricLarge,    metricContext,    industry,    executionType,    featuredImage  }
export type CASE_STUDIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  kicker: string | null;
  cardHeadline: string | null;
  metricLarge: string | null;
  metricContext: string | null;
  industry: "energy" | "financial" | "healthcare" | "manufacturing" | "retail" | null;
  executionType: "ai-data" | "cloud" | "core-systems" | "digital-product" | null;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"servicePage\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    kicker,\n    heroHeadline,\n    heroSubheadline,\n    problemHeadline,\n    problemDescription,\n    solutionDescription,\n    capabilities[]{\n      title,\n      description\n    },\n    proofKicker,\n    proofMetric,\n    proofContext,\n    proofBody,\n    proofCaseStudyLink->{\n      title,\n      \"slug\": slug.current,\n      kicker,\n      metricLarge,\n      metricContext\n    },\n    ctaHeadline,\n    ctaBody,\n    metaTitle,\n    metaDescription\n  }\n": SERVICE_PAGE_QUERYResult;
    "\n  *[_type == \"caseStudy\"] | order(_createdAt desc){\n    _id,\n    title,\n    \"slug\": slug.current,\n    kicker,\n    cardHeadline,\n    metricLarge,\n    metricContext,\n    industry,\n    executionType,\n    featuredImage\n  }\n": CASE_STUDIES_QUERYResult;
  }
}
